### ISSUE TITLE
a tool for adding new learned word

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#14]
I am amazed by the constant improvements made on this tool. Since the focus of CWS is language acquisition I think there should be a option to test users on the most frequent words  (eg go down the frequency list for words, for each word show 3 different pinyin/zhuyins and if the user chooses correctly then add the word to the learned list, if the user selects incorrectly remove it from the learned list). This would be more helpful then letting users proactively adding words to the learned list because it requires them to be knowledgeable of what they know (it requires users not only to know the word 他 but that they know that they know the word 他）

**Comment by chinese-words-separator** [comment]
This is now possible on Recall, just update to 8.24.84.1290

As for deleting/adding a word (from learned words list) based on learner's recall of the word, a separate task is made for it:

[Recall: Randomized selection, remove/add learned word](https://github.com/chinese-words-separator/chinese-words-separator.github.io/issues/15)

Random choices for the zhuyin is also on that task
