### ISSUE TITLE
word search not working for compound words when CWS is on

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#20]
I noticed ever since adding the side annotation of Zhuyin I can't search for compound phrases on Chrome. Here is for example a search for the single character "於 ". Chrome is able to find this character with Zhuyin

https://photos.app.goo.gl/JP6frEAonqRP6yiaA

but now the compound word "屬於" in the same location it is not able to find.

 https://photos.app.goo.gl/St6wSMQj66hHpbXx8

I need to do this to add the word to the learned word list. There does not seem to be a simple way to add the word directly from the ALL HSK list to the Learned Word List. I need to 1) find the word in the text and 2) double click on the word. It would be great if we could directly add words from the All HSK List to the Learned Word List and also have a column in the Learned Word List denoting the date it was learned/added to track progress

**Comment by chinese-words-separator** [comment]
> but now the compound word "屬於" in the same location it is not able to find.
> https://photos.app.goo.gl/St6wSMQj66hHpbXx8

This is a browser limitation, in this case it's a limitation of Chrome. Safari on the other hand can search compound words just fine

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/91402471/228091405-a2ef1649-562d-477c-947e-f264f37592e2.png">

Better to file this issue on Chrome's feature request or bug fix request

> It would be great if we could directly add words from the All HSK List to the Learned Word List 

There's already a mechanism to mark learned words without clicking them one-by-one, make a newline-delimited list of words you already learned, copy it, and then click `Restore learned from clipboard`. e.g., copy the list below..
```
屬於
小公主
电脑
```

..and then click the `Restore learned from clipboard` button

![image](https://user-images.githubusercontent.com/91402471/228092278-57eb0ec5-be33-4fd0-bf9a-b15006deded2.png)

**Comment by chinese-words-separator** [comment]
> and also have a column in the Learned Word List denoting the date it was learned/added to track progress

I will put this in separate issue. Currently, under-the-hood, marking learned words is just marked with a boolean denoted by 'Y'. Many parts of CWS will be impacted when it is changed to date
