### ISSUE TITLE
separating color by tone is incosistent

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#22]
It seems that every time I reopen the browser or re-enable CWS, it will randomly assign different colors for the tones (I chose tone -based separating colors). My daughter finds it confusing that where in one session red denotes the fourth tone, in the next session red denotes the 2nd tone.  Would be very helpful to make the tone color assignments consistent. Thank you

**Comment by chinese-words-separator** [comment]
Never found it inconsistent. Perhaps this is accidentally toggled between session?

<img width="39" alt="image" src="https://user-images.githubusercontent.com/91402471/231599561-40fd9ff7-3e45-4758-b856-32869b8a4c87.png">
