### ISSUE TITLE
Phonetic annotation of Chinese characters is only based on Mainland China/PRC usage

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#23]
There is difference in the *standard/normative* phonetic pronunciation  of various Chinese characters in Mainland China vs Taiwan dictionaries. [This wikipedia page](https://zh.wikipedia.org/wiki/%E6%B5%B7%E5%B3%BD%E5%85%A9%E5%B2%B8%E7%8F%BE%E4%BB%A3%E6%A8%99%E6%BA%96%E6%BC%A2%E8%AA%9E%E7%99%BC%E9%9F%B3%E5%B7%AE%E7%95%B0%E5%88%97%E8%A1%A8) goes into this in some detail. CWS seems to follow only the Mainland China standards even though most users of Zhuyin is based in Taiwan. Could there be an option to choose to annotate the words based on Taiwan's standard pronounciations

[Example](https://photos.app.goo.gl/xZHtYiDBDVTbghPH9)

**Comment by chinese-words-separator** [comment]
Already set the task [here](https://github.com/chinese-words-separator/chinese-words-separator.github.io/issues/12)
