### ISSUE TITLE
chinese word separator

### ISSUE THREAD

**Issue by Nati130** [chinese-words-separator/chinese-words-separator.github.io#25]
I would like to have the option of reading only they pinyin without the chinese characters and to have the same function like word separator and the translation when I hover on a word. That would be great!

**Comment by chinese-words-separator** [comment]
Before:

<img width="639" alt="image" src="https://github.com/chinese-words-separator/chinese-words-separator.github.io/assets/91402471/fd64daeb-d7f4-4469-9e16-bc873710b872">


After:

<img width="634" alt="image" src="https://github.com/chinese-words-separator/chinese-words-separator.github.io/assets/91402471/fd9e5df5-8afe-4cc5-912b-f3ba3e8c2800">

To convert hanzi to pinyin temporarily on a site:

<img width="745" alt="image" src="https://github.com/chinese-words-separator/chinese-words-separator.github.io/assets/91402471/2aa8ce2e-738d-4d13-be8f-573745609604">

To convert hanzi to pinyin permanently on all sites:

<img width="564" alt="image" src="https://github.com/chinese-words-separator/chinese-words-separator.github.io/assets/91402471/609da254-32b0-48bb-9fed-330ff4dee897">

Caveat, when hanzi is converted to pinyin, only the sentence dictionary is working. You cannot use word dictionary on pinyin-converted page. Word dictionary functionality (in fact, all the functionalities of Chinese words separator) fundamentally works on page's hanzi content. Word dictionary scan Chinese word (hanzi) from the page even when there is no custom tag that holds the original content (hanzi). Hence, it is difficult (if not impossible) for word dictionary to scan the matching vocabulary for a given pinyin, shì can either mean 是, 事, or 市. Sentence dictionary can "scan" the original Chinese word (hanzi) even when the page is converted to pinyin as sentence dictionary does not look at the content of the page directly, it look for information in CWS's custom tags. When sentence dictionary is activated, the page's original content are wrapped in custom container tags, those container tags contains the original content (hanzi), hence sentence dictionary can work even when the page's hanzis are converted to pinyin, word dictionary cannot

Expect many functionalities not to work when you exclusively use pinyin-converted page

Converting hanzi to pinyin is available on 8.24.84.1890, currently in Pending review in Chrome web store
