### ISSUE TITLE
Copy highlighted text to clipboard

### ISSUE THREAD

**Issue by victorlin** [chinese-words-separator/chinese-words-separator.github.io#31]
The keyboard shortcuts are great, they make this extension very powerful. One thing that I wish could be done more easily is to copy just the highlighted text to the clipboard. The only built-in action is to copy the entire definition entry or some parts of it.

The workaround I found was to remap the definition copy actions to an arbitrary unused character (couldn't unmap the actions) then use the system ⌘+C to copy the text. This isn't terrible, but I'm wondering if you would consider supporting this as a built-in function.

**Comment by victorlin** [comment]
Sorry, let me clarify. I am already using the word dictionary. In your video example, I get this in the clipboard:

> 願望	愿望	yuànwàng	desire｡ wish	…

when I only want "願望"

**Comment by chinese-words-separator** [comment]
Double-click the word in the page, and then press Ctrl+C

You can also use an extension to automate the copying of double-clicked word into the clipboard, so there's no need to press Ctrl+C, e.g., https://chromewebstore.google.com/detail/double-click-to-clipboard/lhchgmglnhifidmalgeohaagfhmckpmo

You can also right click the word in the text, the text will be automatically selected by word (a word can be multiple characters), Chrome is smart enough to detect word boundaries and will automatically select multiple characters if the Chinese word is made of multiple characters. After right-clicking a word, then select Copy

**Comment by chinese-words-separator** [comment]
When you are using CWS's words separator and if Chrome did not select the whole word as the word is a compound word, you  need to use triple-click on the word. Caveat, when not using CWS, triple-clicking a text selects the whole paragraph, not the compound word only

Double-clicking the 生 in 生命科學 will only select 生命, triple-clicking 生 will select the whole word 生命科學

**Comment by victorlin** [comment]
Thank you, I will continue to use ⌘+C.
