### ISSUE TITLE
Wrong conversion (Simplified to Traditional characters)

### ISSUE THREAD

**Issue by Zerarzgdow** [chinese-words-separator/chinese-words-separator.github.io#4]
CWS misconverted 「法」 as 「灋」 when treated as separate character.
![CWS wrong conversion](https://user-images.githubusercontent.com/15002249/195209923-d82c49ec-fccd-4ebe-b91c-7b6613cc5250.png)

**Comment by chinese-words-separator** [comment]
Hmm.. I put guard into places to prevent over-conversion, like when converting from simplified to traditional, the traditional/simplified 后 (queen/back) should not convert to traditional 後 (back) , as traditional queen 后 is still 后 on simplified version, and the traditional back 後 is mapped to 后 when China simplified 後

On websites with simplified content, 后 is ambiguous if it is a stand-alone character (especially on websites that uses stand-alone characters such as SRS websites) or when there are no surrounding context to a character. Hence the stand-alone 后 should not convert 後 when converting from simplified to traditional, which CWS implemented correctly. Sadly, Google Translate converts 后 to 後 when converting from simplified to traditional; Google Translate should not do that, standalone 后 is ambiguous if a website uses simplified characters, I digress. 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/91402471/195221114-7ea06bca-738d-483f-86b9-6c58bdeb60c2.png">

<img width="714" alt="image" src="https://user-images.githubusercontent.com/91402471/195221341-0f4a7f46-9335-40fc-ba0e-3ef6fd8887f3.png">

As for the 法 being converted to 灋, looks like both you and Google Translate are correct. Characters should not be converted if the target conversion just maps to a variant

Thanks for reporting this

**Comment by chinese-words-separator** [comment]
Corrected now, will release it on version 8.24.84.701

Google need to process the pending version (8.24.84.700) before it accepts publishing another

<img width="764" alt="image" src="https://user-images.githubusercontent.com/91402471/195241978-439c92c9-3cf0-47d8-87de-c8cc05796ff1.png">
